title: The Mantle
author: Chris
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Chris. It serves as a directory for all my projects and a place for my thoughts.
theme: minima
